import { useMatch } from '@/stores/match.store'
import { setActivePinia, createPinia } from 'pinia'

describe('Subject Store', () => {
  beforeEach(() => {
    setActivePinia(createPinia())
  })

  // NOTE: 测试接口 'match/getMatchPasswordPage' 的数据'
  it.skip('should return 1 record', async () => {
    const store = useMatch()
    await expect(store.getMatchsByPage(10, 1)).resolves
      .toMatchInlineSnapshot(`
      [
        [
          {
            "baseTitle": null,
            "classIdList": null,
            "classNo": "0922201",
            "grade": null,
            "isCheat": null,
            "isEnd": null,
            "isStart": null,
            "matchId": "1597184056519331841",
            "matchPassword": null,
            "questionDtoList": null,
            "status": "考完了",
            "studentId": null,
            "studentName": "沈金晶",
            "studentNo": "092218114",
            "subjectName": "高数A",
            "taskId": null,
            "taskPassword": "4139",
            "taskStartToEnd": "2022年11月26日 08:00-10:00",
          },
          {
            "baseTitle": null,
            "classIdList": null,
            "classNo": "0922201",
            "grade": null,
            "isCheat": null,
            "isEnd": null,
            "isStart": null,
            "matchId": "1597184056519331842",
            "matchPassword": null,
            "questionDtoList": null,
            "status": "考试中",
            "studentId": null,
            "studentName": "陈楷豪",
            "studentNo": "092220104",
            "subjectName": "高数A",
            "taskId": null,
            "taskPassword": "123456",
            "taskStartToEnd": "2022年11月26日 08:00-10:00",
          },
          {
            "baseTitle": null,
            "classIdList": null,
            "classNo": "0922201",
            "grade": null,
            "isCheat": null,
            "isEnd": null,
            "isStart": null,
            "matchId": "1597184056519331843",
            "matchPassword": null,
            "questionDtoList": null,
            "status": "作弊",
            "studentId": null,
            "studentName": "丁杰",
            "studentNo": "092220108",
            "subjectName": "高数A",
            "taskId": null,
            "taskPassword": "123456",
            "taskStartToEnd": "2022年11月26日 08:00-10:00",
          },
          {
            "baseTitle": null,
            "classIdList": null,
            "classNo": "0922201",
            "grade": null,
            "isCheat": null,
            "isEnd": null,
            "isStart": null,
            "matchId": "1597184056519331844",
            "matchPassword": null,
            "questionDtoList": null,
            "status": "考试中",
            "studentId": null,
            "studentName": "范雨晨",
            "studentNo": "092220110",
            "subjectName": "高数A",
            "taskId": null,
            "taskPassword": "7337",
            "taskStartToEnd": "2022年11月26日 08:00-10:00",
          },
          {
            "baseTitle": null,
            "classIdList": null,
            "classNo": "0922201",
            "grade": null,
            "isCheat": null,
            "isEnd": null,
            "isStart": null,
            "matchId": "1597184056519331845",
            "matchPassword": null,
            "questionDtoList": null,
            "status": "考试中",
            "studentId": null,
            "studentName": "谷琦",
            "studentNo": "092220112",
            "subjectName": "高数A",
            "taskId": null,
            "taskPassword": "1094",
            "taskStartToEnd": "2022年11月26日 08:00-10:00",
          },
          {
            "baseTitle": null,
            "classIdList": null,
            "classNo": "0922201",
            "grade": null,
            "isCheat": null,
            "isEnd": null,
            "isStart": null,
            "matchId": "1597184056519331846",
            "matchPassword": null,
            "questionDtoList": null,
            "status": "考试中",
            "studentId": null,
            "studentName": "胡宇昂",
            "studentNo": "092220114",
            "subjectName": "高数A",
            "taskId": null,
            "taskPassword": "1737",
            "taskStartToEnd": "2022年11月26日 08:00-10:00",
          },
          {
            "baseTitle": null,
            "classIdList": null,
            "classNo": "0922201",
            "grade": null,
            "isCheat": null,
            "isEnd": null,
            "isStart": null,
            "matchId": "1597184056519331847",
            "matchPassword": null,
            "questionDtoList": null,
            "status": "考试中",
            "studentId": null,
            "studentName": "江正杰",
            "studentNo": "092220116",
            "subjectName": "高数A",
            "taskId": null,
            "taskPassword": "6936",
            "taskStartToEnd": "2022年11月26日 08:00-10:00",
          },
          {
            "baseTitle": null,
            "classIdList": null,
            "classNo": "0922201",
            "grade": null,
            "isCheat": null,
            "isEnd": null,
            "isStart": null,
            "matchId": "1597184056519331848",
            "matchPassword": null,
            "questionDtoList": null,
            "status": "考试中",
            "studentId": null,
            "studentName": "冷浩",
            "studentNo": "092220118",
            "subjectName": "高数A",
            "taskId": null,
            "taskPassword": "2675",
            "taskStartToEnd": "2022年11月26日 08:00-10:00",
          },
          {
            "baseTitle": null,
            "classIdList": null,
            "classNo": "0922201",
            "grade": null,
            "isCheat": null,
            "isEnd": null,
            "isStart": null,
            "matchId": "1597184056519331849",
            "matchPassword": null,
            "questionDtoList": null,
            "status": "考试中",
            "studentId": null,
            "studentName": "施颖杰",
            "studentNo": "092220120",
            "subjectName": "高数A",
            "taskId": null,
            "taskPassword": "4426",
            "taskStartToEnd": "2022年11月26日 08:00-10:00",
          },
          {
            "baseTitle": null,
            "classIdList": null,
            "classNo": "0922201",
            "grade": null,
            "isCheat": null,
            "isEnd": null,
            "isStart": null,
            "matchId": "1597184056519331850",
            "matchPassword": null,
            "questionDtoList": null,
            "status": "未开考",
            "studentId": null,
            "studentName": "吴宝杰",
            "studentNo": "092220122",
            "subjectName": "高数A",
            "taskId": null,
            "taskPassword": "5903",
            "taskStartToEnd": "2022年11月26日 08:00-10:00",
          },
        ],
        18,
      ]
    `)
  })
})
