<template>
  <div class="question-container" data-test="questionList">
    <h1 text-center>
      常熟理工学院 XXX 学院 马克思主义思想道德期末考试试卷
    </h1>
    <p>一、单选题</p>
    <RadioList :data="radioList" />
    <p>二、多选题</p>
    <CheckboxList :data="checkboxList" />
    <p>三、判断题</p>
    <JudgeList :data="judgeList" />
  </div>
</template>

<script setup lang="ts">
import RadioList from './RadioList.vue'
import CheckboxList from './CheckboxList.vue'
import JudgeList from './JudgeList.vue'
import { computed, reactive } from 'vue'
import mitt from '@/utils/mitt'
const questionList = reactive([
  {
    questionId: '1595984141935997030',
    baseId: null,
    questionType: 1,
    questionList:
      '自由竞争资本主义必然向垄断资本主义过渡，这种必然性根源于（    ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '资本积累的一般规律',
      '资本有机构成不断提高',
      '资本对外扩张的结果',
      '资本主义的基本矛盾',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984141868888209',
    baseId: null,
    questionType: 1,
    questionList:
      '关于社会存在和社会意识的辩证关系，以下说法错误的是（    ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '社会意识反作用于社会存在',
      '社会存在决定社会意识',
      '社会意识反映社会存在',
      '社会意识消极被动地受制于社会存在',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984141801779276',
    baseId: null,
    questionType: 1,
    questionList:
      '世界上唯一不变的是变。这一论断的含义是指（    ）',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '变与不变是绝对对立的',
      '世界上只有变，没有不变',
      '变是世界的本原',
      '变是绝对的，不变是相对的',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984141868888227',
    baseId: null,
    questionType: 1,
    questionList:
      '区分不同生产方式、判定社会经济结构的客观依据是（    ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '生产中人与人的关系',
      '生产工具',
      '产品分配关系',
      '生产资料所有制关系',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984141998911556',
    baseId: null,
    questionType: 1,
    questionList:
      '从时间上看，远大理想与共同理想的关系是（）的关系。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '全人类理想与全体中国人民理想',
      '最终理想与阶段性理想',
      '理想与现实',
      '最高纲领与最低纲领',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984141868888091',
    baseId: null,
    questionType: 1,
    questionList: '直接经验和间接经验的关系是(  )',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '知识的“源”和“流”的关系',
      '物质与意识的关系',
      '现实和理论的关系',
      '存在和思维的关系',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984141801779277',
    baseId: null,
    questionType: 1,
    questionList: '空间是指（    ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '物质运动的顺序性',
      '物质运动的广延性',
      '物质运动的规律性',
      '物质运动的持续性',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984141801779320',
    baseId: null,
    questionType: 1,
    questionList:
      '“居安思危”这个成语体现的哲学道理是（    ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '矛盾既具有普遍性又具有特殊性',
      '矛盾双方在一定条件下可以相互转化',
      '内因和外因相结合推动事物发展',
      '事物发展是量变和质变的统一',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984141935996963',
    baseId: null,
    questionType: 1,
    questionList: '人的本质属性是（    ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '理性',
      '自然属性',
      '社会属性',
      '精神属性',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984141868888082',
    baseId: null,
    questionType: 1,
    questionList:
      '科学思维能力的根本要求和集中体现是（  ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '战略思维能力',
      '辩证思维能力',
      '创新思维能力',
      '历史思维能力',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984141998911500',
    baseId: null,
    questionType: 1,
    questionList:
      '产业资本循环中实现价值增殖的阶段是(     )',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '购买阶段',
      '生产阶段',
      '运输阶段',
      '销售阶段',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984141868888150',
    baseId: null,
    questionType: 1,
    questionList:
      '承认我们的一切知识具有相对性，就会（  ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '陷入诡辩论',
      '导致怀疑主义',
      '防止相对主义',
      '防止绝对主义',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984141998911505',
    baseId: null,
    questionType: 1,
    questionList:
      '某工厂原工作日为8小时，必要劳动时间和剩余劳动时间各为4小时，若采用绝对剩余价值生产方法，增加剩余劳动时间2小时，则剩余价值率为（  ）',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: ['180%', '150%', '120%', '200%'],
    questionCorrectList: null,
  },
  {
    questionId: '1595984141935997156',
    baseId: null,
    questionType: 1,
    questionList:
      '如果部门劳动生产率下降，同一劳动在单位时间内创造的（）',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '价值量增加，单位产品的价值量增加',
      '价值量减少，单位产品的价值量减少',
      '使用价值量减少，单位产品的价值量减少',
      '使用价值量减少，单位产品的价值量增加',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984141935996978',
    baseId: null,
    questionType: 1,
    questionList:
      '（  ）的发展为经济全球化提供了适宜的企业组织形式。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '世贸组织',
      '商品流通',
      '跨国公司',
      '金融国际化',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984141734670347',
    baseId: null,
    questionType: 1,
    questionList:
      '俄国十月社会主义革命的胜利，开创了世界历史的新纪元，使科学社会主义开始 （    ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '从空想变为科学',
      '从理论变为现实',
      '从一种模式变为多种模式的转变',
      '从一国变为多国的实践',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984141998911551',
    baseId: null,
    questionType: 1,
    questionList:
      '我国现在尚处在社会主义社会的初级阶段，对于整个社会主义时期究竟会有多长，究竟要经历哪些发展阶段，何时才能达到共产主义社会，还需要随着历史的发展进一步认识和探索。理解正确的是（）',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '探索证明共产主义和“土豆烧牛肉”差不多',
      '探索证明可以跑步进入共产主义',
      '对社会主义的长期性应有充分的估计，绝不可急于迈进',
      '探索证明社会主义长不了',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984141868888141',
    baseId: null,
    questionType: 1,
    questionList: '真理的一元性是由（  ）决定的。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '真理的多样性',
      '真理的客观性',
      '真理的主观性',
      '真理的相对性',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984141868888099',
    baseId: null,
    questionType: 1,
    questionList:
      '在中国，为了治疗疾病，古代就产生了中医学。这说明（    ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '认识是实践的目的',
      '认识产生于实践的需要',
      '实践是认识的本质',
      '实践是检验认识的标准',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984141935996947',
    baseId: null,
    questionType: 1,
    questionList:
      '被剥削阶级的斗争不同程度地打击了剥削阶级的统治，迫使其作出一些让步和调整，而推动生产力的发展和社会进步，这体现阶级斗争在社会形态（    ）过程中的作用。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: ['质变', '运动', '量变', '发展'],
    questionCorrectList: null,
  },
  {
    questionId: '1595984141801779228',
    baseId: null,
    questionType: 1,
    questionList:
      '马克思主义中国化最新理论成果是（　　）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '毛泽东思想',
      '习近平新时代中国特色社会主义理论',
      '列宁主义',
      '邓小平理论',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984141801779248',
    baseId: null,
    questionType: 1,
    questionList:
      '物质和意识的对立只有在非常有限的范围内才有绝对的意义，超过这个范围便是相对的了，这个范围是指（   ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '物质和意识何者与社会生活的关系更密切',
      '物质和意识何者更为重要',
      '物质和意识是否具有统一性',
      '物质和意识何者为第一性',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984141998911528',
    baseId: null,
    questionType: 1,
    questionList:
      '( )是马克思主义追求的根本价值目标,也是共产主义社会的根本特征。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '产品极大丰富',
      '实现人的自由而全面的发展',
      '人的精神境界极高',
      '生产力极大提高',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984141868888230',
    baseId: null,
    questionType: 1,
    questionList: '生产关系的产生和变化根源于（   ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '社会关系',
      '上层建筑',
      '经济基础',
      '生产力',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984141868888195',
    baseId: null,
    questionType: 1,
    questionList:
      '自然地理环境对社会发展所起的作用是（    ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '直接决定人类的社会生活过程',
      '促进或延缓社会发展',
      '通过决定社会制度的性质和社会制度的更替来影响社会发展',
      '通过对科学技术的影响来影响社会发展',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984141935996991',
    baseId: null,
    questionType: 1,
    questionList:
      '国家垄断资本主义的根本特征在于（    ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '国家垄断资本在数量上的优势',
      '国家对经济进行干预和调节',
      '私人垄断资本的主导地位',
      '国私共有的垄断资本',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984141734670351',
    baseId: null,
    questionType: 1,
    questionList:
      '坚持一切从实际出发，理论联系实际，实事求是，在实践中检验真理和发展真理，是马克思主义最重要的（    ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '理论基础',
      '理论经验',
      '理论内容',
      '理论品质',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984141935996986',
    baseId: null,
    questionType: 1,
    questionList:
      '各种垄断组织虽然形式不同，但本质上都是为了（    ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '避免两败俱伤',
      '联合起来共同发展',
      '获取高额垄断利润',
      '相互之间竞争',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984141801779236',
    baseId: null,
    questionType: 1,
    questionList:
      '为马克思主义产生提供经济、社会历史条件的是（    ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '共产主义团体的出现',
      '资本主义经济的发展',
      '工人行动的兴起',
      '马克思和恩格斯的革命实践',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984141868888187',
    baseId: null,
    questionType: 1,
    questionList: '解放思想，与时俱进，就是要（  ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '不受任何框框的束缚，思想上达到绝对自由',
      '突破落后观念的束缚，坚持实事求是',
      '不受任何约束，做到随心所欲',
      '抛弃原有的一切观念，重新评价一切',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984141998911502',
    baseId: null,
    questionType: 1,
    questionList:
      '在资本主义生产过程中，具体劳动的作用是（    ）',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '创造剩余价值',
      '创造劳动力的价值',
      '转移劳动力价值',
      '转移生产资料的价值',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984141868888228',
    baseId: null,
    questionType: 1,
    questionList:
      '历史上在社会中占统治地位的生产关系的两大类型是（    ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '资本主义生产关系和社会主义生产关系',
      '原始社会公有制的生产关系和社会主义社会公有制的生产关系',
      '以雇佣劳动为基础的生产关系和以自由劳动为基础的生产关系',
      '以生产资料公有制为基础的生产关系和以生产资料私有制为基础的生产关系',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984141935997011',
    baseId: null,
    questionType: 1,
    questionList: '垄断资本主义对经济的发展（    ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '既无积极作用，又无消极作用',
      '只有积极作用，没有消极的作用',
      '只有消极作用，没有积极作用',
      '既有积极作用，又有消极作用',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984141935997137',
    baseId: null,
    questionType: 1,
    questionList:
      '今年某西欧国家纺织部门预付资本共计100亿美元，资本有机构成9：1，工人平均月工资2000美元，由于技术的进步，纺织部门资本有机构成变为19:1。这时在不增加预付资本的情况下，纺织部门排挤出的失业工人为（    ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: ['25万', '50万', '20万', '30万'],
    questionCorrectList: null,
  },
  {
    questionId: '1595984141935996990',
    baseId: null,
    questionType: 1,
    questionList:
      '国家垄断资本主义的产生和发展表明（    ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '为向社会主义过渡提供了最完备的物质准备',
      '私有制已经被公有制所代替',
      '资本主义仍然具有强大的生命力',
      '社会主义制度很快就要建立',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984141935997106',
    baseId: null,
    questionType: 1,
    questionList:
      '在一切社会中，社会财富都是由：（    ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '剩余价值构成的',
      '使用价值构成的',
      '价值构成的',
      '货币构成的',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984141998911526',
    baseId: null,
    questionType: 1,
    questionList:
      '在共产主义社会，工业活动和农业活动、城市生活和乡村生活、脑力劳动和体力劳动之间在活动方式和环节等方面的差异( )。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '完全不消除',
      '能消除',
      '不会完全消除',
      '不能消除',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984141801779261',
    baseId: null,
    questionType: 1,
    questionList:
      '世界的统一性问题说的是，世界万物（    ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '是否普遍联系',
      '是否有共同的规律',
      '是否运动发展',
      '是否有一个共同的本原',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984141801779246',
    baseId: null,
    questionType: 1,
    questionList: '哲学上两大对立的基本派别是（    ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '唯物主义和唯心主义',
      '辩证法和形而上学',
      '可知论和不可知论',
      '一元论和二元论',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984141868888169',
    baseId: null,
    questionType: 1,
    questionList:
      '人们在实践中所必须遵循的、以满足人们需要为内容的、特定的实践目标，是实践的（  ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '客观尺度',
      '唯一尺度',
      '真理尺度',
      '价值尺度',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142523199566',
    baseId: null,
    questionType: 2,
    questionList: '实现共产主义是（）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '想起来很美，就是不可实现',
      '人们的想象',
      '人类历史发展的必然趋势',
      '历史没有规律',
      '马克思主义最崇高的社会理想',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142523199542',
    baseId: null,
    questionType: 2,
    questionList: '资本积累规模的大小取决于（）',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '所用资本和所费资本之间的差额',
      '劳动生产率的高低',
      '预付资本量的大小',
      '对工人的剥削程度',
      '资本有机构成的高低',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142456090928',
    baseId: null,
    questionType: 2,
    questionList:
      '马克思指出：“无论哪一个社会形态，在它所能容纳的全部生产力发挥出来以前，是决不会灭亡的”。社会主义最终取代资本主义，需要经历一个很长的历史时期，这是因为（    ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '落后国家首先走上社会主义道路，在物质技术基础上超过资本主义需要相当长时期',
      '社会主义在一国或几国首先胜利，面对国外敌对势力的破坏，可能出现倒退和反复',
      '资本主义借鉴社会主义的一些做法，阶级矛盾和社会矛盾有一定程度的缓和',
      '资本主义生产关系还有调整的余地，在一定程度上允许生产力继续发展',
      '资本主义已经积累了雄厚的经济实力和丰富的统治经验',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142456090719',
    baseId: null,
    questionType: 2,
    questionList:
      '从感性认识向理性认识飞跃的条件（    ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '用科学的观点分析、概括感性材料',
      '用辩证思维方法对感性材料进行加工',
      '将感性材料去粗取精、去伪存真、由此及彼、由表及里地制作加工',
      '感性材料合乎实际',
      '感性材料十分丰富',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142388981773',
    baseId: null,
    questionType: 2,
    questionList: '马克思主义的当代价值在于（  ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '指引当代中国发展的行动指南',
      '探索宇宙的公理',
      '观察当代世界变化的认识工具',
      '解决环境问题的最佳理性方案',
      '引领人类社会进步的科学真理',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142456090631',
    baseId: null,
    questionType: 2,
    questionList:
      '下列各项中属于辩证唯物主义时空观内容的有（　　　）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '时间和空间既是绝对的，又是相对的',
      '时间和空间是物质的惟一特性',
      '时间和空间是物质运动的存在形式　　　',
      '时间和空间是有限性和无限性的统一　　',
      '时间和空间与物质运动不可分割',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142456090636',
    baseId: null,
    questionType: 2,
    questionList: '从意识的本质看，意识是（　　）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '人脑的分泌物',
      '人脑的机能和属性　',
      '自然界长期发展的产物　 　 　　',
      '社会历史的产物',
      '客观世界的主观映象',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142456090929',
    baseId: null,
    questionType: 2,
    questionList:
      '从20世纪60年代开始，邓小平同志通过不断探索，在1992年南方谈话中，他将社会主义本质概括为：“社会主义的本质，是解放生产力，发展生产力，消灭剥削，消除两极分化，最终达到共同富裕。”这一概括的理论意义在于（    ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '是对科学社会主义的重大理论贡献',
      '对我们正确把握社会主义的特征具有重要指导意义',
      '是探索建设有中国特色社会主义的重大理论成果',
      '把对社会主义的认识提高到了新的水平',
      '为如何建设中国特色社会主义开辟了广阔的道路',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142523199602',
    baseId: null,
    questionType: 2,
    questionList:
      '青年一代有（），国家就有前途，民族就有希望。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '有金钱',
      '有担当',
      '有本领',
      '有理想',
      '有宗教信仰',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142456090839',
    baseId: null,
    questionType: 2,
    questionList:
      '在关于人民群众和杰出人物的历史作用问题上，历史唯物主义认为（    ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '前者可以改变历史发展规律，后者不能改变历史发展规律',
      '二者共同创造历史',
      '前者是创造历史过程中的决定力量，后者是非决定力量',
      '二者的作用都要受到一定历史条件和社会发展客观规律的制约',
      '二者在历史上的作用是等同的',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142456090734',
    baseId: null,
    questionType: 2,
    questionList:
      '下列观点属于主观唯心主义真理观的是（  ）',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '“真理是‘绝对理念’的自我显现”',
      '真理是“观念与主体感觉相符合”',
      '“真理存在于观念之中”',
      '“真理是思维与它的先验形式相一致”',
      '“真理是某种超验的、永恒的‘理念’”',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142456090638',
    baseId: null,
    questionType: 2,
    questionList:
      '马克思主义关于物质和意识关系的全面看法是（    ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '物质决定意识，意识是人脑的机能',
      '意识第一性，物质第二性',
      '物质第一性，意识第二性',
      '物质决定意识，意识反作用于物质',
      '物质是意识的根源，意识是对物质的反映',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142456090865',
    baseId: null,
    questionType: 2,
    questionList:
      '对当代资本主义发生了一些新变化正确认识是（  ）',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '没有改变马克思主义关于资本主义的基本论断的科学性',
      '经济危机依然是资本主义不可克服的痼疾',
      '并没有克服资本主义的基本矛盾',
      '根源于资本主义基本矛盾的金融危机',
      '并没有改变资本主义制度的本质',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142523199596',
    baseId: null,
    questionType: 2,
    questionList: '实现共产主义的长期性表现在（    ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '从资本主义到社会主义有一个过渡时期',
      '当代社会主义已经被资本主义所击败',
      '西方资本主义发展得很好，不可能转变为社会主义',
      '共产主义的第一阶段社会主义是一个长期的历史过程　',
      '从社会主义到共产主义有一个过渡时期',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142456090712',
    baseId: null,
    questionType: 2,
    questionList:
      '在人的认识活动中，反映特性与能动的创造特性的关系是（   ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '创造离不开反映，创造存在于反映之中',
      '反映也离不开创造，反映是在创造过程中实现的',
      '是不可分割的',
      '是同一本质的两种不同的功能，是一个硬币的两面',
      '是人类认识的两种不同的本质',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142523199524',
    baseId: null,
    questionType: 2,
    questionList:
      '“工资不是它表面上呈现的那种东西，不是劳动的价值或价格，而是劳动力的价值或价格的掩蔽形式。”说明资本主义的工资（    ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '是劳动力价值或价格的转化形式',
      '其本质是劳动力的价值或价格',
      '掩盖了资本主义剥削关系',
      '工资是不可以理解的现象',
      '等于工人创造的新价值',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142523199509',
    baseId: null,
    questionType: 2,
    questionList: '存在商品经济的社会包括（    ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '奴隶社会',
      '资本主义社会',
      '社会主义社会',
      '共产主义社会',
      '封建社会',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142456090858',
    baseId: null,
    questionType: 2,
    questionList:
      '2008年国际金融危机以来资本主义西方国家的经济生活、政治生活和社会民生等方面都出现了各种问题。表现在（   ）',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '经济发展“失调”',
      '社会融合机制“失效”',
      '政治体制“失灵”',
      '资本国际化',
      '垄断组织追求垄断利润',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142456090669',
    baseId: null,
    questionType: 2,
    questionList: '矛盾的普遍性和特殊性的关系是（  ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '形式和内容的关系',
      '相互依存、相互转化的关系',
      '共性和个性的关系',
      '绝对和相对的关系',
      '整体和部分的关系',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142456090681',
    baseId: null,
    questionType: 2,
    questionList:
      '唯物辩证法的否定观认为,在人类历史上新社会代替旧社会都是（    ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '社会的自我否定',
      '对旧社会既克服又保留',
      '社会的发展环节和联系环节的统一',
      '社会发展的连续性和非连续性的统一',
      '包含肯定的否定',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142456090658',
    baseId: null,
    questionType: 2,
    questionList: '下列选项中属于因果联系的有 （   ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '虚心使人进步，骄傲使人落后',
      '冬去春来，夏尽秋至',
      '磨擦生热，热胀冷缩',
      '勤学出智慧，实践出真知',
      '月晕而风，础润而雨',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142456090629',
    baseId: null,
    questionType: 2,
    questionList: '唯物主义的时空观认为（　　）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '时间、空间是物质运动的存在形式',
      '时间、空间既是相对的又是绝对的　',
      '时间、空间既是有限的又是无限的',
      '时间、空间是整理感觉材料的工具',
      '时间、空间与物质运动不可分割　  　',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142456090834',
    baseId: null,
    questionType: 2,
    questionList:
      '英雄史观之所以产生，其深刻的根源在于（    ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '人们的认识停留于历史现象的表面，把活跃在历史前台的少数英雄人物及其意识的作用加以夸大并绝对化',
      '剥削阶级的思想家为了维护本阶级的利益，需要宣扬英雄史观，抹杀广大人民群众的历史作用',
      '人们懒于思考，目光仅仅停留在历史前台',
      '人类曾经经历过一个英雄时代，英雄史观是那个时代所留下的印迹',
      '同社会生产力水平较低，大多数人从事物质资料的生产活动，少数人从事政治统治、垄断精神文化生活有关',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142456090821',
    baseId: null,
    questionType: 2,
    questionList:
      '剥削阶级实现阶级统治的基本途径有（    ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '发展生产',
      '经济剥削',
      '政治统治',
      '思想控制',
      '社会革命',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142523199507',
    baseId: null,
    questionType: 2,
    questionList: '劳动生产率的变化是（    ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '与一定时间的商品价值总量无关',
      '与单位商品的价值量成反比',
      '与单位商品的价值量成正比',
      '与使用价值量成正比',
      '与使用价值量成反比',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142456090646',
    baseId: null,
    questionType: 2,
    questionList:
      '下列观点中，属于唯物辩证法的总观点的有（    ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '肯定与否定的观点',
      '永恒发展的观点',
      '对立统一的观点',
      '普遍联系的观点',
      '量变和质变的观点',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142456090876',
    baseId: null,
    questionType: 2,
    questionList:
      '垄断价格的形成并没有否定价值规律，因为（    ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '垄断价格围绕价值波动',
      '垄断价格不能完全脱离商品的价值',
      '垄断价格改变的只是价值规律作用的表现形式',
      '垄断价格围绕生产价格波动',
      '全社会的商品价格总额和商品价值总额仍然一致',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142523199517',
    baseId: null,
    questionType: 2,
    questionList:
      '价值增殖过程是超过一定点的价值形成过程，这里的“一定点”是指（    ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '剩余劳动时间的终点',
      '生产时间的起点',
      '剩余劳动时间的起点',
      '必要劳动时间的起点',
      '必要劳动时间的终点',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142523199586',
    baseId: null,
    questionType: 2,
    questionList: '共产主义实现的必然性体现为（    ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '社会主义运动的实践，特别是社会主义国家的兴起和不断发展用事实证明',
      '共产主义是依据社会发展规律设立的社会发展目标',
      '人类社会发展规律所决定的   ',
      '共产主义是马克思恩格斯坚持科学的立场、观点和方法作出的科学预测',
      '以资本主义社会的基本矛盾发展为依据的',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142523199513',
    baseId: null,
    questionType: 2,
    questionList:
      '决定私人劳动和社会劳动矛盾的经济条件是（    ）。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: [
      '生产资料私有制',
      '社会分工',
      '自然分工',
      '生产资料属于不同的所有者',
      '商品生产和商品交换',
    ],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142963601454',
    baseId: null,
    questionType: 3,
    questionList:
      '生产工具是区分不同生产方式、判断社会经济结构性质的客观依据。（    ）',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: ['错', '对'],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142837772449',
    baseId: null,
    questionType: 3,
    questionList:
      '“物极必反，相反相成”体现了量变引起质变的哲学道理。（    ）',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: ['对', '错'],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142837772331',
    baseId: null,
    questionType: 3,
    questionList:
      '唯物史观和剩余价值学说使社会主义由空想成为科学。（    ）',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: ['错', '对'],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142963601529',
    baseId: null,
    questionType: 3,
    questionList:
      '评价历史人物必须坚持历史分析方法和阶级分析方法的统一。（    ）',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: ['对', '错'],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142963601563',
    baseId: null,
    questionType: 3,
    questionList:
      '国有垄断资本，即国家作为垄断资本家的总代表直接掌握的垄断资本。其中国家投资是形成国有垄断资本的主要途径，而国有企业是国有垄断资本的组织形式。（    ）',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: ['对', '错'],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142837772322',
    baseId: null,
    questionType: 3,
    questionList:
      '马克思主义哲学是时代精神的精华。（    ）',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: ['错', '对'],
    questionCorrectList: null,
  },
  {
    questionId: '1595984143026516079',
    baseId: null,
    questionType: 3,
    questionList:
      '到共产主义社会，阶级消灭了，阶级剥削和压迫不复存在，阶级斗争也随之消失。（）',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: ['错', '对'],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142963601693',
    baseId: null,
    questionType: 3,
    questionList: '暴力革命是无产阶级革命的一般形式。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: ['对', '错'],
    questionCorrectList: null,
  },
  {
    questionId: '1595984143026515972',
    baseId: null,
    questionType: 3,
    questionList:
      '具体劳动和抽象劳动是同一劳动的两个方面或两重属性，而不是两次劳动，更不是两种劳动。（    ）',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: ['对', '错'],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142963601560',
    baseId: null,
    questionType: 3,
    questionList:
      '国家垄断资本主义是资本社会化的最高形式，因而在相当程度上克服了私人垄断资本社会化程度较低的局限性。（    ）',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: ['对', '错'],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142837772447',
    baseId: null,
    questionType: 3,
    questionList:
      '质变和量变的区别在于是否出现部分质变。（    ）',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: ['对', '错'],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142963601717',
    baseId: null,
    questionType: 3,
    questionList:
      '具体劳动和抽象劳动是两次劳动，前者生产使用价值，后者创造商品价值。（    ）',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: ['对', '错'],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142963601631',
    baseId: null,
    questionType: 3,
    questionList:
      '资本主义所以能在历史上起革命作用，根本原因是顺应历史发展的客观规律，打破了束缚生产力发展的腐朽的封建所有制生产关系，建立了资本主义生产关系，为生产力的发展开辟了广阔道路。（    ）',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: ['错', '对'],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142963601509',
    baseId: null,
    questionType: 3,
    questionList:
      '现实的人是基于自身需要和社会需要而从事一定实践活动的、处于一定社会关系中的、具有能动性的人。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: ['错', '对'],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142837772326',
    baseId: null,
    questionType: 3,
    questionList:
      '实践的观点是马克思主义基本的观点，实践性是马克思主义的本质特性。（    ）',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: ['对', '错'],
    questionCorrectList: null,
  },
  {
    questionId: '1595984143026516170',
    baseId: null,
    questionType: 3,
    questionList:
      '展望未来，我国青年一代肩负历史重任，必将大有可为，但本领不够，无法大有作为。（）',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: ['错', '对'],
    questionCorrectList: null,
  },
  {
    questionId: '1595984143026516005',
    baseId: null,
    questionType: 3,
    questionList:
      '资本主义生产过程是劳动过程和价值形成过程的统一。（    ）',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: ['错', '对'],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142837772423',
    baseId: null,
    questionType: 3,
    questionList:
      '没有脱离偶然的必然，没有脱离必然的偶然。（    ）',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: ['对', '错'],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142963601428',
    baseId: null,
    questionType: 3,
    questionList: '“历史是任人打扮的女孩子。”（    ）',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: ['错', '对'],
    questionCorrectList: null,
  },
  {
    questionId: '1595984143026516066',
    baseId: null,
    questionType: 3,
    questionList:
      '社会生产力高度发展，产品极大丰富，是实现共产主义的必要条件。（）',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: ['错', '对'],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142963601609',
    baseId: null,
    questionType: 3,
    questionList:
      '为了获取高额垄断利润，垄断资本家可以任意抬高垄断价格。（    ）',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: ['错', '对'],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142963601608',
    baseId: null,
    questionType: 3,
    questionList:
      '所谓垄断，简单地说就是“独占”，是指资本主义少数大企业为了获得高额垄断利润联合起来独占生产和市场。（    ）',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: ['错', '对'],
    questionCorrectList: null,
  },
  {
    questionId: '1595984143026516096',
    baseId: null,
    questionType: 3,
    questionList:
      '在共产主义社会，这个劳动时间将会大大缩短。人们只需要从事较少时间的劳动，就能为社会创造出足够的物质财富。（）',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: ['错', '对'],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142963601685',
    baseId: null,
    questionType: 3,
    questionList:
      '马克思主义的经典作家为后人提供了各国社会主义发展道路的现成理论方案',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: ['错', '对'],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142837772495',
    baseId: null,
    questionType: 3,
    questionList:
      '主观唯心主义和客观唯心主义在认识论上都属于唯心主义先验论。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: ['错', '对'],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142837772336',
    baseId: null,
    questionType: 3,
    questionList:
      '在理论联系实际的过程中，逐步学会运用马克思主义的立场、观点和方法去分析和解决问题本领。（    ）',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: ['错', '对'],
    questionCorrectList: null,
  },
  {
    questionId: '1595984143026516086',
    baseId: null,
    questionType: 3,
    questionList:
      '在共产主义社会，不仅社会是和谐的，而且社会与自然之间也将达成和谐。（）',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: ['对', '错'],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142963601566',
    baseId: null,
    questionType: 3,
    questionList:
      '近年来，西方社会不断出现不同群体、阶层的矛盾与冲突，甚至社会动荡。',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: ['错', '对'],
    questionCorrectList: null,
  },
  {
    questionId: '1595984142837772496',
    baseId: null,
    questionType: 3,
    questionList: '一切唯物主义都是能动的反映论。（    ）',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: ['错', '对'],
    questionCorrectList: null,
  },
  {
    questionId: '1595984143026515969',
    baseId: null,
    questionType: 3,
    questionList:
      '商品之所以具有二因素，是由体现在商品中的劳动二重性决定的。（    ）',
    questionAnswer: null,
    questionCorrect: null,
    baseTitle: null,
    questionAnswerList: ['错', '对'],
    questionCorrectList: null,
  },
])
const radioList = computed(() => {
  return questionList.filter(
    item => item.questionType === 1
  )
})
const checkboxList = computed(() => {
  return questionList.filter(
    item => item.questionType === 2
  )
})
const judgeList = computed(() => {
  return questionList.filter(
    item => item.questionType === 3
  )
})

mitt.on('finishTask', () => {
  console.log('finishTask', questionList)
})
</script>

<style lang="scss" scoped>
.question-container {
  width: 80vw;
}
</style>
