// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdminAside: typeof import('./components/admin/AdminAside.vue')['default'];
    BreadCrumb: typeof import('./components/BreadCrumb.vue')['default'];
    Card: typeof import('./components/Card.vue')['default'];
    Carousel: typeof import('./components/Carousel.vue')['default'];
    Checkbox: typeof import('./components/Checkbox.vue')['default'];
    Content: typeof import('./components/Content.vue')['default'];
    Drawer: typeof import('./components/Drawer.vue')['default'];
    Footer: typeof import('./components/Footer.vue')['default'];
    Form: typeof import('./components/admin/Form.vue')['default'];
    FormItem: typeof import('./components/admin/FormItem.vue')['default'];
    Header: typeof import('./components/Header.vue')['default'];
    ImportInfo: typeof import('./components/ImportInfo.vue')['default'];
    Layout: typeof import('./components/Layout.vue')['default'];
    List: typeof import('./components/List.vue')['default'];
    Main: typeof import('./components/Main.vue')['default'];
    MainLayout: typeof import('./components/MainLayout.vue')['default'];
    Menu: typeof import('./components/Menu.vue')['default'];
    Modal: typeof import('./components/Modal.vue')['default'];
    Nav: typeof import('./components/Nav.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    Search: typeof import('./components/Search.vue')['default'];
    Select: typeof import('./components/Select.vue')['default'];
    Switch: typeof import('./components/Switch.vue')['default'];
    Table: typeof import('./components/Table.vue')['default'];
    Upload: typeof import('./components/Upload.vue')['default'];
  }
}
